[package]
name = "hashtable-comparison"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "hashtable-comparison"


[dependencies]
wyhash = "0.5.0"

[dependencies.fnv]
git = "https://github.com/servo/rust-fnv"
default-features = false